# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
# Configuration for Maven (Java)
  - package-ecosystem: "maven" # Set to "maven" for Java Projects
    directory: "/" # Location of pom.xml (root of the repo)
    schedule:
      interval: "weekly" # How often to check for updates (daily, weekly, monthly)

    # Limit the number of open pull requests
    # This helps prevent PR overload.
    open--pull-requests-limit: 10

    # Configure the commit message format
    commit-message:
      # Prefix for the commit message "chore" is common for automated tasks like dependency updates.
      prefix: "chore"
      # Include the scope in the commit message (e.g., chore(deps): update spring-boot to 3.2.x)
      include: "scope"
    
