version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: friends_and_places_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: friends_and_places_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d friends_and_places_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: friends_and_places_postgres_data
