# H2 In-Memory Database Configuration for Tests/CI
spring:
  datasource:
    url: jdbc:h2:mem:fapdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop # Ensures a clean database for each test run
    properties:
      hibernate:
        format_sql: true

# JWT Configuration for Test Environment
jwt:
  secret: testSecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours
