# Default Application Configuration
spring:
  application:
    name: FriendsAndPlaces
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: thread
        format_sql: true
        jdbc:
          non_contextual_creation: true

# Springdoc OpenAPI Configuration
springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  pathsToMatch: /api/v1/**
  packages-to-scan: de.whs.wi.friends_and_places.controller
  packages-to-exclude: de.whs.wi.friends_and_places.error
  override-with-generic-response: false
  auto-tag-classes: true

# External API Configuration
external-api:
  base-url: https://api.geoapify.com/v1
  connection-timeout: 5000
  read-timeout: 10000
