# Default Application Configuration
spring:
  application:
    name: FriendsAndPlaces

# Springdoc OpenAPI Configuration
springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  pathsToMatch: /api/v1/**
  packages-to-scan: de.whs.wi.friends_and_places.controller
  packages-to-exclude: de.whs.wi.friends_and_places.error
  override-with-generic-response: false
  auto-tag-classes: true
