# Default Application Configuration
spring:
  application:
    name: FriendsAndPlaces

# Default profile to activate if none specified (e.g., for local running without a profile)
  profiles:
    active: dev

# General JPA Settings
  jpa:
    open-in-view: false # Good practice for REST APIs to avoid lazy loading issues

# Server Port
server:
  port: 8080 # Default port for the application