# Friends and Places Application Configuration
# This file contains the configuration settings for the Friends and Places application.
# Spring Configuration properties are defined here.
spring:
  application:
    name: friends_and_places
  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yml
  # DataSource Configuration
  datasource:
    dirver-class-name: org.postgresql.Driver
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: thread
        format_sql: true
        jdbc.lob.non_contextual_creation: true

# Server Configuration
server:
  error:
    include-message: always
  port: 8080