# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop" ] # Trigger on pushes to main and develop branches
  pull_request:
    branches: [ "main" ] # Trigger on pull requests targeting main

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu virtual machine

    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to check out the repository code

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Javer Version of Spring Boot app
        distribution: 'temurin' # Recommended distribution for OpenJDK
        cache: maven # Cache Maven dependencies to speed up builds
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml # Run Maven build, -B for batch mode (non-interactive)

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
